// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXHFkbwGp9G-7P7LL_UjUhw6Gw8_UIQRQ',
    appId: '1:168114649559:web:ed2ec80a67142ceb0ff392',
    messagingSenderId: '168114649559',
    projectId: 'trippo-73fd7',
    authDomain: 'trippo-73fd7.firebaseapp.com',
    databaseURL: 'https://trippo-73fd7-default-rtdb.firebaseio.com',
    storageBucket: 'trippo-73fd7.firebasestorage.app',
    measurementId: 'G-8P0Z0CNG06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxXyLrfPq42UzbVPNOMnFrCDuqgMqm6mQ',
    appId: '1:168114649559:android:df5b9fcd5ba803220ff392',
    messagingSenderId: '168114649559',
    projectId: 'trippo-73fd7',
    databaseURL: 'https://trippo-73fd7-default-rtdb.firebaseio.com',
    storageBucket: 'trippo-73fd7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-mock-key-ios',
    appId: '1:168114649559:ios:mockiosid',
    messagingSenderId: '168114649559',
    projectId: 'trippo-73fd7',
    storageBucket: 'trippo-73fd7.appspot.com',
    iosBundleId: 'com.example.toyApp',
  );
}
